### ISSUE TITLE
Build errors in devel/xorg-macros and x11/xorgproto

### ISSUE THREAD

**Issue by Echo-8-ERA** [shkhln/freebsd-lib32-companion-ports#1]
Hi, I was doing a fresh install of 12.1 using your ports tree and I ran into build errors in a couple ports. I believe it's due to these lines:
https://github.com/shkhln/freebsd-lib32-companion-ports/blob/394323b7115ca714cacf7711307430967a3a1923/devel/xorg-macros/Makefile#L15-L17

https://github.com/shkhln/freebsd-lib32-companion-ports/blob/394323b7115ca714cacf7711307430967a3a1923/x11/xorgproto/Makefile#L10-L12

I edited those lines to become one line each, and the build continued fine. I'd make a PR with those changes, but I don't trust my understanding of makefiles to be good enough to tell if that was the correct course of action.

**Comment by shkhln** [comment]
Yeah, sorry. Looks like a botched rebase again.
